# test cicd for terraform 2

name: Terraform

on:
  push:
    branches: [master]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    env:
      working-directory: ../../
    defaults:
      run:
        working-directory: ${{ env.working-directory }}    
    steps:
      - name: Where am i
        id: where
        run: pwd
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check 
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
